<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
  <%if data["list"]%>
  <title>SpeedyDelivery: <%$list.name%></title>
  <%else%>
  <title>SpeedyDelivery: Home</title>
  <%endif%>

<meta http-equiv="content-type" content="application/xhtml+xml; charset=UTF-8" />

<link rel="stylesheet" type="text/css" media="screen" href="/static/Underground.css" />

</head>

<body>
<!-- wrap starts here -->
<div id="wrap">

		<!-- header -->
		<div id="header">			
					
			<span id="slogan"> mail list services</span>
			
			<!-- tabs -->
			<ul>
				<li id="current"><a href="/"><span>Home</span></a></li>
				<li><a href="index.html"><span>About</span></a></li>			
			</ul>
											
		</div>
		
		<div id="header-logo">			
			
			<div id="logo">speedy<span class="red">delivery</span></div>		
			
			<form method="post" class="search" action="#">
				<p><input name="search_query" class="textbox" type="text" />
  				<input name="search" class="searchbutton" value="Search" type="submit" /></p>
			</form>
						
		</div>
		
       	<div id="main">

<div><font color="red"><i><%flash%></i></font></div>

<%yield%>

	</div> <!-- main -->

<!-- wrap ends here -->
</div>
		
<!-- footer starts here -->
<div class="footer">
	
		<p>	
		    &copy; 2007-2011 H William Welliver III

            &nbsp;&nbsp;&nbsp;&nbsp;

	    	<a href="http://hg.welliver.org/SpeedyDelivery">speedydelivery</a>

		    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		    <a href="/">Home</a>
		</p>
		
</div>	
	
</body>
</html>
