<%paginator var="$library" store="songs" size="25"%>
<%$songcount%> songs in library.

<table width="95%">
    <tr>
        <td>
Show: <%page_size_selector paginator="$songs" size="10, 25, 50"%>
</td>
<td colspan="3" align="right">
<%page_filter paginator="$songs" field="title"%>
</td>
    </tr>
    <tr>
        <th align="left" width="30%">Title</th>
        <th align="left" width="30%">Album</th>
        <th align="left" width="30%">Artist</th>
        <th align="left" width="10%">Time</th>
    </tr>
<%foreach var="$songs.page" val="song"%>

<tr>
    <td><%$song.title%></td>
    <td><%$song.album%></td>
    <td><%$song.artist%></td>
    <td><%format_length var="$song.length"%></td>
</tr>
<%end%>
</table>
<% if data->songs_prevurl%>
<a href="<%$songs_prevurl%>">&lt;&lt; Prev</a>
<%else%>
  &lt;&lt; Prev
<%endif%>
<%page_selector paginator="$songs" window="5"%>
<% if data->songs_nexturl%>
<a href="<%$songs_nexturl%>">Next &gt;&gt;</a>
<%else%>
  Next &gt;&gt; 
<%endif%>
