<title>Password Retrieval</title>
   <h3>Password Retrieval</h3>
<p/>
Enter your username in the form below and click on "Locate." Your account password will be emailed to the address on record for that account.
   <p/>
<%flash%>
<p/>
<form action="" method="post">
Username: <input type="string" name="username" value="<%$username%>"/><br/>
<p/>
<input type="submit" name="action" value="Locate"/>
</form>

